# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
- repo: local
  hooks:
    - id: version-env
      name: Writing version to .env
      description: Reading library __version__ and saving it to .env
      entry: pipenv run python -m board_game_scraper.version_env
      language: system
      always_run: true
      pass_filenames: false
