version: '3'

services:
    bgg:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 10800 # 3 hours
            DONT_RUN_BEFORE_SEC: 3600 # 1 hour
            # GOOGLE_APPLICATION_CREDENTIALS: /app/gs.json
            TELNETCONSOLE_ENABLED: 1
            TELNETCONSOLE_USERNAME: scrapy
            TELNETCONSOLE_PASSWORD: recommend.games
        ports:
            - 6023:6023
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
            # - ../recommend-games-server/gs.json:/app/gs.json
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-hotness:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-hotness
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg_hotness']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 21600 # 6 hours
            DONT_RUN_BEFORE_SEC: 10800 # 3 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-abstract:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-abstract
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_abstract',
            '-a', 'bgg_path=abstracts/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-children:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-children
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_children',
            '-a', 'bgg_path=childrensgames/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-customizable:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-customizable
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_customizable',
            '-a', 'bgg_path=cgs/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-family:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-family
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_family',
            '-a', 'bgg_path=familygames/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-party:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-party
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_party',
            '-a', 'bgg_path=partygames/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-strategy:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-strategy
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_strategy',
            '-a', 'bgg_path=strategygames/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-thematic:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-thematic
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_thematic',
            '-a', 'bgg_path=thematic/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-rankings-war:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings-war
        build: '.'
        command: [
            'python', '-m', 'board_game_scraper', 'bgg_rankings',
            '--feeds-subdir', 'bgg_rankings_war',
            '-a', 'bgg_path=wargames/browse/boardgame',
        ]
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    dbpedia:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-dbpedia
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'dbpedia']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    luding:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-luding
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'luding']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    spielen:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-spielen
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'spielen']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    wikidata:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-wikidata
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'wikidata']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    news:
        image: registry.gitlab.com/mshepherd/news-scraper:0.18.0
        container_name: bg-scraper-news
        volumes:
            - ./feeds/news/output:/root/output
            - ~/.aws:/root/.aws
        env_file: .env
        environment:
            ENVIRONMENT: docker
            OUTPUT_DIR: s3://scrape.news.recommend.games
            ELASTICSEARCH_STORAGE_ENABLED: 0
            COUCHBASE_CACHE_ENABLED: 1
            COUCHBASE_ENTITY_LINKING_ENABLED: 0
            LOGSTASH_HOST: ''
            LOGSTASH_PORT: ''
            LOGSTASH_PROTOCOL: none
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT
