version: '3'

services:
    bgg:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 10800 # 3 hours
            DONT_RUN_BEFORE_SEC: 3600 # 1 hour
            TELNETCONSOLE_ENABLED: 1
            TELNETCONSOLE_USERNAME: scrapy
            TELNETCONSOLE_PASSWORD: recommend.games
            SCRAPE_PREMIUM_USERS_CONFIG_DIR: /app/premium
        ports:
            - 6023:6023
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
            - ../recommend-games-config/users/premium:/app/premium
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    bgg-hotness:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-hotness
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg_hotness']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 21600 # 6 hours
            DONT_RUN_BEFORE_SEC: 10800 # 3 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    dbpedia:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-dbpedia
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'dbpedia']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    luding:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-luding
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'luding']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    spielen:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-spielen
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'spielen']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    wikidata:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-wikidata
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'wikidata']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 36000 # 10 hours
            DONT_RUN_BEFORE_SEC: 21600 # 6 hours
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT

    news:
        image: registry.gitlab.com/mshepherd/news-scraper:0.18.0
        container_name: bg-scraper-news
        volumes:
            - ./feeds/news/output:/root/output
            - ~/.aws:/root/.aws
        env_file: .env
        environment:
            ENVIRONMENT: docker
            OUTPUT_DIR: s3://scrape.news.recommend.games
            ELASTICSEARCH_STORAGE_ENABLED: 0
            COUCHBASE_CACHE_ENABLED: 1
            COUCHBASE_ENTITY_LINKING_ENABLED: 0
            LOGSTASH_HOST: ''
            LOGSTASH_PORT: ''
            LOGSTASH_PROTOCOL: none
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT
