version: '3'

services:
    bgg:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 10800 # 3 hours
            DONT_RUN_BEFORE_SEC: 3600 # 1 hour
            GOOGLE_APPLICATION_CREDENTIALS: /app/gs.json
        volumes:
            - ./feeds:/app/feeds
            - ./images:/app/images
            - ../recommend-games-server/gs.json:/app/gs.json
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    bgg-rankings:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-bgg-rankings
        build: '.'
        command: ['bash', 'scrape_rankings.sh']
        env_file: .env
        environment:
            MAX_SLEEP_PROCESS: 60
        volumes:
            - ./feeds:/app/feeds
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    sites:
        image: registry.gitlab.com/recommend.games/board-game-scraper:${LIBRARY_VERSION}
        container_name: bg-scraper-sites
        build: '.'
        command: ['bash', 'scrape_sites.sh']
        env_file: .env
        environment:
            MAX_SLEEP_PROCESS: 60
        volumes:
            - ./feeds:/app/feeds
        restart: unless-stopped
        stop_grace_period: 30m
        stop_signal: SIGINT

    news:
        image: registry.gitlab.com/mshepherd/news-scraper:0.18.0
        container_name: bg-scraper-news
        volumes:
            - ./feeds/news/output:/root/output
            - ~/.aws:/root/.aws
        env_file: .env
        environment:
            ENVIRONMENT: docker
            OUTPUT_DIR: s3://scrape.news.recommend.games
            ELASTICSEARCH_STORAGE_ENABLED: 0
            COUCHBASE_CACHE_ENABLED: 1
            COUCHBASE_ENTITY_LINKING_ENABLED: 0
            LOGSTASH_HOST: ''
            LOGSTASH_PORT: ''
            LOGSTASH_PROTOCOL: none
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT
