version: '3.7'

services:
    bgg-hotness:
        image: bg-scraper:latest
        container_name: bg-scraper-bgg-hotness
        build: '.'
        command: ['python', '-m', 'board_game_scraper', 'bgg_hotness']
        env_file: .env
        environment:
            CLOSESPIDER_TIMEOUT: 21600 # 6 hours
            DONT_RUN_BEFORE_SEC: 10800 # 3 hours
        volumes:
            - ./feeds:/app/feeds
        restart: always
        stop_grace_period: 15m
        stop_signal: SIGINT
